server:
  port: 8081
accessToken: 18_Raf9oU3Hx3xdBs11g0zqe_onB3uDsFftK_CRRbpbw7Aankq91_v_GRX0wHiVcWAXdBEgRYeujy2rGti-EB1l1pZRXMh6_DEvVVi91GvVI5McrzChHomhIEs6q0yg1_JQWczUg66_Ny5WWUJGWSThAHAZVW
ticket: LIKLckvwlJT9cWIhEQTwfBRdFtoTvF57I8YXxc_D7bilMDpQpfwmjy4gHu3-X9V1AHAf9kJzlOM_Bx-LoMpHyA
wxprops: 
#正式
#  appid: wx0c374e55a8f51dcf
#  appsecret: 8e5a9e02b7ad4fdabc21fd53bc147e96
#测试
  appid: wx414c92f266bf8411
  appsecret: 8f66bf583824bb7c65355de4bd0bfecb
  token: shock
  encodingaeskey: bCzLyIcpVr6IOb73Lxd6vaXYrR56DflhNb7js2SXDmU
  debug: true
weixinapi:
  access-token:
    token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={appid}&secret={appsecret}
    jsapi-ticket: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token={accessToken}&type=jsapi
  menu:
    create: https://api.weixin.qq.com/cgi-bin/menu/create?access_token={accessToken}
  material:
    batchget-material: https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token={accessToken}
spring:
  redis:
    host: 192.168.109.128
    port: 6379
    password: 123456
    timeout: 1000
    database: 0
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100