server:
  port: 8080
wxprops: 
#正式
#  appid: wx0c374e55a8f51dcf
#  appsecret: e2abf67dc2b94c659aeb53006e640e2e
#测试
  appid: wx414c92f266bf8411
  appsecret: 8f66bf583824bb7c65355de4bd0bfecb
  token: shock
  encodingaeskey: bCzLyIcpVr6IOb73Lxd6vaXYrR56DflhNb7js2SXDmU
  debug: true
weixinapi:
  oauth2:
    authorize: https://open.weixin.qq.com/connect/oauth2/authorize?appid={appid}&redirect_uri={redirectUri}&response_type=code&scope={scope}&state={state}#wechat_redirect
  access-token:
    token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={appid}&secret={appsecret}
    jsapi-ticket: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token={accessToken}&type=jsapi
  menu:
    create: https://api.weixin.qq.com/cgi-bin/menu/create?access_token={accessToken}
  material:
    batchget-material: https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token={accessToken}
spring:
  redis:
    host: 192.168.109.128
    port: 6379
    password: 123456
    timeout: 1000
    database: 0
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100